server:
  url: http://192.168.5.88
  port: 8091
  reactive:
    session:
      cookie:
        http-only: true
        secure: false
        same-site: lax
        path: /

spring:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaozhi?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: xiaozhi
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 120000
      pool-name: DatebookHikariCP
      max-lifetime: 120000
      connection-timeout: 10000000
      connection-test-query: SELECT 1
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
  groovy:
    template:
      check-template-location: false

# 抗遗忘地址
forget:
  url: http://113.250.13.197:24914

mybatis:
  mapper-locations: classpath*:com/xiaozhi/mapper/*.xml

logging:
  level:
    root: INFO
    org.springframework: INFo
    com.xiaozhi.dao: DEBUG
    com.xiaozhi.websocket: DEBUG
    io.github.imfangs.dify.client.impl.StreamEventDispatcher: ERROR

email:
  smtp:
    username: xxxx
    password: xxxx